# Generated by Django 4.2.1 on 2023-05-20 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotional', '0002_alter_devotional_devotion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devotional',
            name='devotion_date',
            field=models.DateField(default=datetime.date(2023, 5, 20), verbose_name='Devotion date'),
        ),
    ]
